name: 功能建议
description: 提出新功能或改进建议
title: "[建议]: "
labels: ["enhancement", "request"]
body:
  - type: checkboxes
    id: confirmations
    attributes:
      label: 确认事项
      description: 请勾选以下确认项
      options:
        - label: 我已搜索过现有 Issue，没有类似问题
          required: true
  - type: dropdown
    id: game
    attributes:
      label: 游戏
      description: 你想对哪个游戏做出建议？
      options:
        - 技能国象
        - 群友抽卡
  - type: textarea
    id: requests
    attributes:
      label: 建议内容
      description: 请详细描述您的建议或反馈
      placeholder: 您的建议将帮助我们改进...
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 您认为这个建议的重要程度
      options:
        - 低 - 有更好，没有也行
        - 中 - 能提升体验
        - 高 - 急需的功能
      default: 1
